getgenv().RobberyToggles = {
    Jewelry_Store = true,
    Power_Plant = true,
    Crown_Jewel = true,
    Cargo_Plane = true,
    Museum = true,
    Rising_Bank = true,
    Crater_Bank = true,
    Tomb = true,
    Oil_Rig = true,
    Cargo_Train = true,
    Mansion = true,
    Airdrop = true,
    Passenger_Train = true,
    Bank_Truck = true,
}
